### PR TITLE
Db setup

### PR DESCRIPTION
**Pull request by KeijiTadashi**

### CODE REVIEW

**Review by Windemuller — CHANGES_REQUESTED** [review]
If I only create a chapter 4, and create a lesson that references to that chapter, the lesson thinks it belongs to chapter 1 although there is no chapter 1.

**Review by Windemuller — DISMISSED** [review]
Position API has a POST option that does not allow the user to specify which user the position should be updated, resulting in an error.

**Comment by KeijiTadashi** [comment]
to update a student's position use /position/[student_id]/ with the set_lesson = [the current lesson number (NOT it's id)], set_chapter = [the current chapter number (NOT it's id)].
With the assignment of lesson to a chapter: in the body chapter = [chapter_id]; which when you assign it should be 1 (if you only create one chapter), however, the number of the chapter itself should be 4.
I realize now that this is inconsistent and will change the assignment of lesson to chapter to instead use the number of the chapter instead of the id. Though it does assign the correct chapter to the lesson, so technically not a bug :)

**Comment by Windemuller** [comment]
Fair enough, hadn't thought about that, but I do indeed think that chapter number/ lesson number would make more sense.

**Review by Windemuller — APPROVED** [review]
👍

**Pull request merged**
